= Getting Started
:toc:
:toclevels: 3

The Identity Proxy uses the https://componentsjs.readthedocs.io/en/latest/[componentsjs] DI framework to let you enable the desired features of the Proxy by simply adding handlers to a JSON-LD config file.

[[passthrough]]
== PassThroughHttpRequestHandler

The foundation of the Proxy rests on the `PassThroughHttpRequestHandler`. This is a handler that takes any request, simply sends it on to a given upstream server, and returns the response. By adding handlers to a chain, you can make changes to the request before it is sent to the upstream, and also add things to the response before sending it back to the client.

The `PassThroughHttpRequestHandler` can be configured as follows:

[source, json]
----
{
    "@id": "urn:dgt-id-proxy:default:PassThroughHandler",
    "@type": "PassThroughHttpRequestHandler",
    "host": "upstreamhost.com",
    "port": 80,
    "scheme": "http:",
    "proxyUrl": "http://proxyhost.com"
}
----

NOTE: The `https:` scheme is supported as well.

NOTE: This handler will convert all outgoing and incoming headers to lowercase.

[[encodinganddecoding]]
== Encoding and Decoding Tokens

If you plan on adding handlers to the token endpoint other than the `PassThroughHttpRequestHandler`, you will need to add a `JwtDecodeHandler` and a 'JwtEncodeHandler' to the chain of handlers on the token endpoint.

This is because, internally, the handlers expect a JSON object for certain tokens. This is is because claims need to be added or changed in, for example, the Access Token. If each handler would have to consistently decode, change, and then encode the token again that would be inefficient. So it's only done once.

[[decode]]
=== JwtDecodeHandler

The config for the `JwtDecodeHandler` is as follows:

[source, json]
----
{
    "@id": "urn:dgt-id-proxy:default:JwtDecodeHandler",
    "@type": "JwtDecodeHandler",
    "jwtFields": [
        "token_field"
    ],
    "upstreamUrl": "http://urlofupstream.com",
    "verifyJwk": true
}
----

The `jwtFields` parameter is a list of fields containing a JWT token that should be decoded (most commonly this will be `access_token` and/or `id_token`), and `verifyJwk` is boolean that tells the proxy to verify the JWK that was used to sign the tokens.

[[encode]]
=== JwtEncodeHandler

The config for the `JwtEncodeHandler` is as follows:

[source, json]
----
{
    "@id": "urn:dgt-id-proxy:default:JwtEncodeHandler",
    "@type": "JwtEncodeHandler",
    "jwtFields":[
        { 
            "@type": "JwtField",
            "field": "token_field", 
            "type": "at+jwt" 
        }
    ],
    "pathToJwks": "/path/to/jwk-file.json",
    "proxyUrl": "http://urlofproxy.com"
}
----

The `jwtFields` parameter is a list of objects of the type `JwtField` and includes a `field` pointing to a token that should be encoded and a `type` that should be set as the token's `typ` claim (commonly `jwt`, or for Access Tokens `at+jwt`)

[[together]]
== Putting them together

We can put all of these handlers together on an endpoint (the token endpoint) as follows:

[source, json]
----
{
    "@id": "urn:dgt-id-proxy:default:TokenEndpoint",
    "@type": "HttpHandlerRoute",
    "operations": [
        {
            "@type": "HttpHandlerOperation",
            "method": "POST",
            "publish": false
        },
        {
            "@type": "HttpHandlerOperation",
            "method": "OPTIONS",
            "publish": false
        }
    ],
    "handler": {
        "@type": "PipeThroughHandler",
        "handlers": [
            {
              "@id": "urn:dgt-id-proxy:default:PassThroughHandler"
            },
            {
              "@id": "urn:dgt-id-proxy:default:JwtDecodeHandler"
            },
            {
              "@id": "urn:dgt-id-proxy:default:JwtEncodeHandler"
            }
        ]
    },
    "path": "/token"
}
----

Because we gave our handlers id's, we can reference them by their ids, which makes the endpoints a lot more readable. Notice that we are using a `PipeThroughHandler`. This handler will simply pass whatever is passed to it to the first handler, take the response from the first handler and pass it to the second handler, and so on until it reaches the end of the chain. The decoder and encoder only need the response containing the JWTs, they don't need to do anything with the request.

So with this config when a request is sent to the /token endpoint of the proxy it would send the request to the upstream server, and when it responds with a token response the given tokens will be decoded and subsequently encoded. With these basics in order, we can start adding handlers to these endpoints.

Take a look at our xref:features.adoc[Features] to see how other handlers can be configured to fill in the gaps for an upstream Identity Provider and allow for Solid compliant OIDC requests.
