import { Handler } from '@digita-ai/handlersjs-core';
import { HttpHandler, HttpHandlerContext, HttpHandlerResponse } from '@digita-ai/handlersjs-http';
import { of, throwError, Observable, switchMap, map } from 'rxjs';
import { v4 as uuidv4 } from 'uuid';
import { KeyValueStore } from '@digita-ai/handlersjs-storage';

/**
 * A { Handler<HttpHandlerContext, HttpHandlerContext> } that handles requests to the Authorization Endpoint. Makes sure the request
 * contains a state parameter so that the original request can be linked to the redirect response
 * to the client's redirect_uri.
 */
export class Auth0LoginStateHandler extends HttpHandler {

  /**
   * Creates an { AuthStateRequestHandler }
   *
   * @param {KeyValueStore<string, boolean>} keyValueStore - store with state as key and a boolean that is
   * true if the client sent the state originally, and false if it was generated by the proxy
   */
  constructor(
    private clientStateToClientRedirectUriStore: KeyValueStore<string, string>,
    private upstreamStateToClientStateStore: KeyValueStore<string, string>,
    private handler: HttpHandler
  ) {

    super();

    if(!clientStateToClientRedirectUriStore){

      throw new Error('A clientStateToClientRedirectUriStore must be provided');

    }

    if(!upstreamStateToClientStateStore){

      throw new Error('A upstreamStateToClientStateStore must be provided');

    }

    if(!handler){

      throw new Error('A handler must be provided');

    }

  }

  /**
   * Handles the request by checking if the client sent state in it's request to the
   * Authorization Endpoint. If the client sent state, the state is saved in the
   * { KeyValueStore<string, boolean> } with the value `true` to indicate that the
   * client sent the state. Otherwise, a state is generated, added to the request url
   * and saved in the { KeyValueStore<string, boolean> } with the value `false` to indicate
   * the client did not send the state.
   *
   *
   * @param {HttpHandlerContext} context
   */
  handle(context: HttpHandlerContext): Observable<HttpHandlerResponse> {

    if (!context) {

      return throwError(() => new Error('Context cannot be null or undefined'));

    }

    if (!context.request) {

      return throwError(() => new Error('No request was included in the context'));

    }

    if (!context.request.headers) {

      return throwError(() => new Error('No headers were included in the request'));

    }

    if (!context.request.url) {

      return throwError(() => new Error('No url was included in the request'));

    }

    const state = context.request.url.searchParams.get('state');

    if (!state) {

      return throwError(() => new Error('No state was included in the request'));

    }

    const redirectUri = context.request.url.searchParams.get('redirect_uri');

    if (!redirectUri) {

      return throwError(() => new Error('No redirectUri was included in the request'));

    }

    this.clientStateToClientRedirectUriStore.set(state, decodeURIComponent(redirectUri));

    return this.handler.handle(context).pipe(
      switchMap((response: HttpHandlerResponse) => {

        const upstreamState = new URL(response.headers.location, 'https://example.com').searchParams.get('state');

        if (!upstreamState) {

          return throwError(() => new Error('No upstreamState was included in the response'));

        }

        this.upstreamStateToClientStateStore.set(upstreamState, state);

        return of(response);

      })
    );

  }

  /**
   * Returns true if the context is valid.
   * Returns false if the context, it's request, or the request's method, headers, or url are not included.
   *
   * @param {HttpHandlerContext} context
   */
  canHandle(context: HttpHandlerContext): Observable<boolean> {

    return context
      && context.request
      && context.request.headers
      && context.request.url
      ? of(true)
      : of(false);

  }

}
