= ID Kit Analysis

The goal of this project is to create a Solid Complaint OIDC Client that gets and stores Access Tokens, and is able to refresh those Tokens so they can be used to gain access to resources.

== Models

[[issuer]]
* Issuer
+
Consists of a `url: URL`, `icon?: URL`, `label?: string`, `description?: string`

* HttpMethod
+
Should contain every method allowed in http (GET, POST, PUT, DELETE, etc.)

* KeyGenerationAlgorithm
+
Should contain all JOSE supported JWA Algorithm Identifiers. Look at jose's xref:https://github.com/panva/jose/blob/v3.14.0/src/runtime/node/generate.ts#L43[generateKeyPair] function to figure out which algorithms are supported and should be part of this Type.

* DiscoveryStringField
+
Should contain a list of all OIDC Discovery fields that return a string. A list can be found here: xref:https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata[OpenID Provider Metadata].

* DiscoveryArrayField
+
Should contain a list of all OIDC Discovery fields that return an array. A list can be found here: xref:https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata[OpenID Provider Metadata].

* DiscoveryField
+
Create a type `DiscoveryField` as follows: `type DiscoveryField = DiscoveryStringField | DiscoveryArrayField`

== Functions

The functions have been split into different modules. All functions should be exported. Import them where necessary.

=== Storage

Code a `TypedKeyValueStore<M>` interface that extends from `KeyValueStore<keyof M, M[keyof M]>`. It should contain the same methods, but make them generic with a parameter `<T extends keyof M>`, and replace all key types `K` by `T` and value types `V` by `M[T]`. (Referenced from https://github.com/digita-ai/semcom/blob/develop/docs/modules/specifications/pages/decentral-nodes.adoc#storage[Semcom Decentralization Analysis docs])

Provide an exported constant `store` that other modules can import to access the store.

=== WebID module

* `getWebIdProfile(webId: URL): Promise<Quad[]>`
+
Should get the profile information from the webID. Check that the response is an RDF document, parse it and return the list of Quads, specifically xref:https://rdf.js.org/data-model-spec/#quad-interface[rdf-js Quads].

* `getIssuerFromWebId(webId: URL): Promise<Issuer>`
+
This function should get the `oidcIssuer` triple from a valid webID profile using the `getWebIdProfile` function and check that the issuer is valid using the `validateIssuer` function. If both are valid, create an xref:id-kit-analysis.adoc#issuer[Issuer] and return it. Take a look at xref:../../../packages/dgt-id-kit/lib/solid-sdk.service.ts[lines 82-90] of the solid-sdk.service.ts for inspiration.

=== Issuer Module

* `getIssuerConfig(issuer:URL): Promise<any>`
+
Should get the information from the /.well-known/openid-configuration endpoint of the issuer, and return the JSON object.


* `validateIssuer(issuer: string): Promise<boolean>`
+
Should validate that the given issuer is valid. The string should be a valid URL, and a valid issuer should advertise that it is solid compliant. If the string is a valid URL, use the URL to get the Issuer's config using `getIssuerConfig`. Check the JSON object it returns for the "solid-oidc-supported" key and value as defined in the https://solid.github.io/authentication-panel/solid-oidc/#discovery[Solid-OIDC spec]. Take a look at xref:../../../packages/dgt-id-kit/lib/solid-sdk.service.ts[lines 19-40] of the solid-sdk.service.ts. Retrieve the configuration using the `getIssuerConfig` function.

* `getDiscoveryInfo<T extends DiscoveryField>(issuer: URL, field: T): T extends DiscoveryStringField ? string : string[]`
+
This function takes a `field`, which can be a DiscoveryStringField or a DiscoveryArrayField. Depending on which type the `field` is, it will return a string or array respectively. This function works using xref:https://www.typescriptlang.org/docs/handbook/2/conditional-types.html[Conditional Types]. Should fetch the issuer's Discovery document using the `getIssuerConfig` function and return the value of the `field`.
+
I implemented an xref:id-kit-analysis.adoc#conditionaltypingexample[example] version of this so it might be a bit easier to understand what it does exactly.

* `getEndpoint(issuer: URL, endpoint: DiscoveryStringField): Promise<string>`
+
Get the specified endpoint from the specified issuer's openid-configuration. `endpoint` should be a field of the Discovery document that returns a string, for example: `authorization_endpoint` or `token_endpoint`. Use the function `getDiscoveryInfo`.

=== OIDC module

* `constructAuthRequestUrl(authorizationEndpoint:string, clientId:string, pkceCodeChallenge: string, responseType: string, scope: string, redirectUri: string): Promise<URL>`
+
This function should create the Authorization Request URL, and return it.
+
Use the Authorization request documentation from the xref:https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1[Classic OIDC spec] and the xref:https://datatracker.ietf.org/doc/html/rfc7636#section-4.3[PKCE spec].

* `authRequest(issuer: URL, clientId: string, scope: string, responseType: string, offline_access: boolean): Promise<void>`
+
Send a solid compliant request to the `authorization_endpoint` of the issuer.
+
Use the `getEndpoint` function to get the `authorization_endpoint`, and use the PKCE functions to generate a `code_challenge`. Create the URL using the `constructAuthRequestUrl` function, and make a request. This function returns void because the request should result in a redirect.

* `tokenRequest(issuer: URL, clientId: string, clientSecret?: string, authorization_code: string, redirectUri: string): Promise<void>`
+
Send a solid compliant request to the `token_endpoint` of the issuer, save the access_token, id_token, and refresh_token - if one was included in the response - in the global `store`.
+
Use the `getEndpoint` function to get the `token_endpoint`, and use the `createDpopProof` function as well.
+
Use the Token Request documentation from the xref:https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3[Classic OIDC spec], the xref:https://datatracker.ietf.org/doc/html/rfc7636#section-4.5[PKCE spec], and the xref:https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop-03#section-5[DPoP spec].

* `refreshTokenRequest(issuer:URL, clientId: string, clientSecret?: string, refresh_token: string, scope: string): Promise<void>`
+
Send a xref:https://openid.net/specs/openid-connect-core-1_0.html#RefreshingAccessToken[request using a refresh_token]. Store the `access_token` and `id_token` in the global `store`.
+
Make sure the request is still valid for both the xref:https://datatracker.ietf.org/doc/html/rfc7636#section-4.5[PKCE spec], and the xref:https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop-03#section-5[DPoP spec].


* `accessResource(resource: URL, method: HttpMethod, body?: string, contentType?: string): Promise<Response>`
+
Send a request with the DPoP bound `access_token` from the `store` to the resource server. Check that the `access_token` has not expired and is still valid. If it is not valid, a new one can be requested using the `refresh_token` and the `refreshTokenRequest` function. Make sure to use the `createDpopProof` function as a valid DPoP proof will be necessary for every request to a resource. In this case the `resource` url will be the `htu`, and the `method` will be the `htm`. Check that the `body` is present for any method that would require it (such as POST). Content-type is not required. If it's omitted, don't add it to the request. This function should return the fetched Response.

=== Client module

* `loginWithIssuer(issuer: URL, clientId: string, scope: string, responseType: string): promise<void>`
+
This function should send an `authRequest` to the issuer.

* `loginWithWebId(webId: URL, clientId: string, scope: string, responseType: string): promise<void>`
+
This function should get the issuer from the webId using the `getIssuerFromWebId` function. Once it has an issuer, it can call the `loginWithIssuer` function to handle the rest of the login.

* `logout(): Promise<void>`
+
Remove the access token and id token from the `store`. This effectively logs the user out on our end.

* `handleIncomingRedirect(`issuer: URL`, `clientId: string`, `clientSecret?: string`, `redirectUri: string`): Promise<void>`
+
This function will handle the redirect after an Authorization Request has been sent. It should get the authorization code from the request (if there is a code). The code will be part of the URL parameters. It can then use this code to send a request to the Token Endpoint by calling the `tokenRequest` function. 

=== DPoP module

* `generateKeys(algorithm: KeyGenerationAlgorithm = 'ES256'): Promise<void>`
+
Generate a private and public key pair using the xref:https://github.com/panva/jose[jose library]. Save the private key as a `KeyLike`, and convert the public key to a `JWK` and save it in the `store`. The algorithm should be `ES256` by default.

* `createDpopProof(htu: string, htm: string): Promise<string>`
+
Create a xref:https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop-03#section-4[DPoP Proof] using the xref:https://github.com/panva/jose[jose library]. Add the public JWK and sign it with the private key from the storage. An example DPoP proof can be found in the xref:../../../demo/demo-client/getAccessTokenAndResource.js[demo-client] (lines 36-50 and 67-79).


[[pkce]]
=== PKCE module

Implement the following functions as part of the PKCE module:

* `generateCodeVerifier(length: number): string`
+
Should generate a `code_verifier` according to xref:https://datatracker.ietf.org/doc/html/rfc7636#section-4.1[section 4.1] of the PKCE spec. Make sure to check that the `length` is within the valid range. Store the `code_verifier` in the `store`.

* `generateCodeChallenge(code_verifier: string): string`
+
Should generate a `code_challenge` according to xref:https://datatracker.ietf.org/doc/html/rfc7636#section-4.2[section 4.2] of the PKCE spec. Specifically note that we MUST use `S256` if we support it, which we will. Do not use the `plain` method to implement this function (that would be kind of useless anyway, since this function would then simply return the `code_verifier` it was given...). Also, make sure to check that the `code_verifier` has an acceptable length.

* `base64UrlEncode(string: string): string`
+
Should base64 URL encode the string and return it.

NOTE: all of these functions have already been implemented in the xref:../../../demo/demo-client/main.js[demo-client] of the identity proxy. (lines 24-39 of main.js). However, since they were part of a demo they were not implemented with the necessary checks. Use those functions as a starting point, and make them more secure.

[[conditionaltypingexample]]
== Conditional Typing Example

Below is an example implementation of `getDiscoveryInfo` using Conditional Typing.

``` javascript
// fields that can return a string
type DiscoveryStringField = 'authorization_endpoint' | `token_endpoint`;

// fields that can return an array
type DiscoveryArrayField = 'scopes';

// DiscoveryField type can be either a DiscoveryStringField or a DiscoveryArrayField
type DiscoveryField = DiscoveryStringField | DiscoveryArrayField;

// to give an easy example, we will use an "any". This simply gets the field from the discoveryInfo parameter and logs some information.
const getDiscoveryInfo = <T extends DiscoveryField>
(discoveryInfo: any, field: T): T extends DiscoveryStringField ? string : string[] => {

  console.log(typeof discoveryInfo[field], ', value: ', discoveryInfo[field]);

  return discoveryInfo[field];

};

// Console output: 'string , value:  string'
getDiscoveryInfo({ authorization_endpoint: 'string', scopes: [ 'array', 'of', 'strings' ] }, 'authorization_endpoint');

// Console output: 'object , value:  [ 'array', 'of', 'strings' ]'
getDiscoveryInfo({ authorization_endpoint: 'string', scopes: [ 'array', 'of', 'strings' ] }, 'scopes');

```



TODO:
* support `state` for the Authorization Request







