:toc:
:toclevels: 3


= Initial setup of the Identity Proxy server
Wouter Termont


== Overview of the proposed solution

In this specification we'll set up the package organization of the compliance proxy in the Identity Broker repo. This analysis covers the basic steps, but you might have to do some extra configuration that is not included here. Assess the correct working of every step, and do not hesitate to contact one of the authors when in doubt.


== Detailed analysis of the suggested implementation

Start by following the xref:setup-package.adoc[general package setup], using the package name `dgt-id-proxy`.


=== A basic server

_Take any unknown interfaces or classes in the next paragraphs to come from `@digita-ai/handlersjs-http` unless otherwise specified._

Start by creating a `NodeHttpStreams` interface, with the fields `requestStream: IncomingMessage` and `responseStream: ServerResponse`, and an abstract `NodeHttpStreamsHandler` class, extending `Handler<NodeHttpStreams>` from our `@digita-ai/handlersjs-core` package. Put these modules in `lib/server`.

Next, in `lib/util`, create an abstract class `Daemon` with nullary `start` and `stop` methods, and a generic abstract class `Server`, extending `Daemon` with a `port` number dependency. Back in `lib/server`, make a `NodeHttpServer` class extending `Server`, taking an extra `NodeHttpStreamsHandler` as dependency, and implementing the `start` and `stop` methods so that it can create a (safely closeable) Node.js `http.Server` that passes requests through the handler.

Also create a `NodeHttpRequestResponseHandler` extending `NodeHttpStreamsHandler`, taking a `HttpHandler` as dependency. Implement its `handle` method so that the `IncomingMessage` is read entirely into a `HttpHandlerRequest`, wrapped in a `HttpHandlerContext` with an undefined `route` field, and passed through the dependency handler's `handle` method (with no `intermediateResponse`); then write the resulting `HttpHandlerResponse` into the `ServerResponse` stream.

Now create a `RoutedHttpRequestHandler` extending `HttpHandler` and taking a list of `HttpHandlerController` as dependency. Implement its `handle` method so that it checks the `HttpHandlerRequest` of the `HttpHandlerContext`, picks a `HttpHandlerRoute` from one of the `HttpHandlerController` (based on the path, method, etc. of the request), and puts a new `HttpHandlerContext` containing the original `HttpHandlerRequest` plus the `HttpHandlerRoute` itself through the `HttpHandler` specified in it.

When all the above is implemented, quickly prototype one or two mock `HttpHandler`, which accepts everything and simply write some mock output to the response stream. Create a `presets` folder in the `config` directory, containing a `server.json` configuration referring to the `dgt-id-broker`, `handlersjs-core` and `handlersjs-http` contexts. Define a configuration for a `NodeHttpServer` with id `urn:dgt-id-broker:default:NodeHttpServer`, passing it a port number and a `NodeHttpRequestResponseHandler` wrapping a `RoutedHttpRequestHandler`. Give this router some mock routes with the mock handlers. Also create a `default.json` configuration in the `config` directory, importing the `presets/server.json` file.

Finally, in `lib` itself, create the main `main.ts` module and add `"dgt-id-proxy": "./dist/main.js"` to the `bin` object of `package.json`. Let the module create a new `ComponentsManager` with the package root as `mainModulePath`; then `register` the default config with the manager's `configRegistry`, let the manager `instantiate` the configured server from its URI, and `start` it. Also create an `index.ts`, simply re-exporting everything from the created modules. Keep this index up to date as you create new ones.

Try to build and run the package. If something is not working as expected, first look into it yourself once more, then ask your partner. If you both don't get what's wrong, ask for help.

If the basic server seems to work, write functional tests for each of the created modules, then run them to check if they indeed do what you'd expect. Also make sure that every aspect of your code is commented thoroughly, so both your partner and others can understand your code without asking you.


//=== Adding observables




//=== Adding routing


