:toc:
:toclevels: 3


= Initial package setup
Wouter Janssens, Stijn Taelemans & Wouter Termont


== Overview of the proposed solution

In this specification we'll set up the package organization in a subrepo of a project. This analysis covers the basic steps, but you might have to do some extra configuration that is not included here. Assess the correct working of every step, and do not hesitate to contact one of the authors when in doubt.


== Detailed analysis of the suggested implementation

While each package is different, and care should be taken to tailor each project to its specific case, there are some general steps that take part in almost every setup.


=== Basic setup

Initialize a Node.js project with the following `package.json` settings:

- a relevant package `name` within the `@digita-ai` scope;
- initial `version` number `0.1.0`;
- a sensible `description`;

// - `Digita`as the `author`;
// - `ISC` as `license`;

- the `main` entry point set to `./dist/public-api.js`;
- the `types` entry point set to `./dist/public-api.d.ts`;

- a `directories` object containing `"lib": "lib"`;
- a `files` list containing `dist`;

- a `repository` information object with `type` set to `git`, containing the SSH `url` of the monorepo of which this package is part, and the `directory` of this package relative to the root.

Install `rimraf` as a first development dependency. 

Create a `.npmrc` file with the following content:

[source,bash]
----
registry=https://registry.npmjs.org/

@digita-ai:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=${NPM_TOKEN}
always-auth=true
----

Also create the `lib` directory with an empty `lib/public-api.ts`. In this file, you'll have to re-export everything you want available in your package.

Finally, add the package to the `.editor.code-workspace` file in the monorepo's root.


=== Typescript

- Install `typescript`,`ts-node` and `@types/node` as development dependencies.

- Add the following scripts to `package.json`:
+
[source,json]
----
"build": "rimraf ./dist && npm run build:ts",
"build:ts": "tsc",
----

- Create a `tsconfig.json` file setting `compileOnSave` to `false`, with `lib` in the `include` list, `node_modules`, `dist`, and `**/*.spec.ts` in the `exclude` list, and containing the following `compilerOptions`:
+
[source,json]
----
"baseUrl": "./",
"outDir": "./dist",
"typeRoots": ["node_modules/@types"],
"strict": true,
"sourceMap": true,
"declaration": true,
"downlevelIteration": true,
"experimentalDecorators": true,
"moduleResolution": "node",
"esModuleInterop": true,
"importHelpers": true,
"noImplicitReturns": true,
"noFallthroughCasesInSwitch": true,
"forceConsistentCasingInFileNames": true,
"target": "es2015",   // set this to a well-supported ES version for client packages, or the latest ES version for Node packages
"module": "commonjs", // set this to the same ES version as target for client packages, or "commonjs" for Node packages
"lib": [
  "es2020",    // set this to the latest ES version, but not "esnext"
  "webworker", // remove for Node packages
  "dom"        // remove for Node packages
]
----

- Also create an additional `tsconfig.spec.json` configuration extending `tsconfig.json`, which adds `./jest.config.ts` to the `files` list and `**/*.spec.ts` to the `include`, then adds a `type` list containing `node` and `jest`, sets `module` to `commonjs`, `target` to `esnext` and `allowJs` `true`, and sets `sourceMap`, `inlineSourceMap`, `declaration` and `strict` to false.


=== ESLint

In the `package.json`, add an `eslintConfig` object with an `extends` list that contains `../../.eslintrc.json`.

Also add the scripts `"lint": "eslint ."` and `"lint:fix": "eslint --fix ."`.


=== Jest

-  Install `jest`, `ts-jest` and `@types/jest` as development dependencies.

- Create a `jest.config.ts` module file importing the `Config` type from `@jest/types`, and exporting as a default a `Config.InitialOptions` object containing the following options: 
+
[source,javascript]
----
testTimeout: 300000,
verbose: true,
preset: 'ts-jest',
testEnvironment: 'node',
rootDir: 'lib',
globals: {
  'ts-jest': {
    babelConfig: true,
    tsconfig: 'tsconfig.json',
  },
}
----

- Add the following scripts to `package.json`:
+
[source,json]
----
"test": "jest --silent",
"test:ci": "jest --runInBand",
"test:e2e": "jest --config ./test/jest-e2e.json",
----


=== Components.js

- Install `componentsjs` as a dependency and `componentsjs-generator` as a development dependency.

- Create a `.componentsignore` file with an empty list in it.

- Also create an empty `config` directory.

- Add both the `config` directory and the `.componentsignore` file to the `files` list of `package.json`.

- Also add the following to `package.json`, substituting `aiv-actueel-inkomen` by the relevant package name: 
+
[source, json]
----
"lsd:module": "https://linkedsoftwaredependencies.org/bundles/npm/@digita-ai/aiv-actueel-inkomen",
"lsd:components": "dist/components/components.jsonld",
"lsd:contexts": {
  "https://linkedsoftwaredependencies.org/bundles/npm/@digita-ai/aiv-actueel-inkomen/^0.0.0/components/context.jsonld": "dist/components/context.jsonld"
},
"lsd:importPaths": {
  "https://linkedsoftwaredependencies.org/bundles/npm/@digita-ai/aiv-actueel-inkomen/^0.0.0/components/": "dist/components/",
  "https://linkedsoftwaredependencies.org/bundles/npm/@digita-ai/aiv-actueel-inkomen/^0.0.0/config/": "config/",
  "https://linkedsoftwaredependencies.org/bundles/npm/@digita-ai/aiv-actueel-inkomen/^0.0.0/dist/": "dist/"
}
----

- Finally, also add and change the following scripts in `package.json`:
+
[source,json]
----
"build": "rimraf ./dist && npm run build:ts && npm run build:components",
"build:ts": "tsc",
"build:components": "componentsjs-generator -s lib -c dist/components -i .componentsignore"
----
