:toc:
:toclevels: 3


= Initial setup of the Identity Proxy server
Wouter Termont


== Overview of the proposed solution

In this specification we'll set up the package organization of the compliance proxy in the Identity Broker repo. This analysis covers the basic steps, but you might have to do some extra configuration that is not included here. Assess the correct working of every step, and do not hesitate to contact one of the authors when in doubt.


== Detailed analysis of the suggested implementation

Start by following the xref:setup-package.adoc[general package setup], using the package name `dgt-id-proxy`.


=== A basic server &#10004;&#65039;

_Take any unknown interfaces or classes in the next paragraphs to come from `@digita-ai/handlersjs-http` unless otherwise specified._

Start by creating a `NodeHttpStreams` interface, with the fields `requestStream: IncomingMessage` and `responseStream: ServerResponse`, and an abstract `NodeHttpStreamsHandler` class, extending `Handler<NodeHttpStreams>` from our `@digita-ai/handlersjs-core` package. Put these modules in `lib/server`.

Next, in `lib/util`, create an abstract class `Daemon` with nullary `start` and `stop` methods, and a generic abstract class `Server`, extending `Daemon` with a `port` number dependency. Back in `lib/server`, make a `NodeHttpServer` class extending `Server`, taking an extra `NodeHttpStreamsHandler` as dependency, and implementing the `start` and `stop` methods so that it can create a (safely closeable) Node.js `http.Server` that passes requests through the handler.

Also create a `NodeHttpRequestResponseHandler` extending `NodeHttpStreamsHandler`, taking a `HttpHandler` as dependency. Implement its `handle` method so that the `IncomingMessage` is read entirely into a `HttpHandlerRequest`, wrapped in a `HttpHandlerContext` with an undefined `route` field, and passed through the dependency handler's `handle` method (with no `intermediateResponse`); then write the resulting `HttpHandlerResponse` into the `ServerResponse` stream.

When all the above is implemented, quickly prototype a `MockHttpHandler`, which accepts everything and simply writes some mock output to the response stream. Create a `presets` folder in the `config` directory, containing a `server.json` configuration referring to the `dgt-id-broker`, `handlersjs-core` and `handlersjs-http` contexts. Define a configuration for a `NodeHttpServer` with id `urn:dgt-id-broker:default:NodeHttpServer`, passing it a port number and a `NodeHttpRequestResponseHandler` wrapping the `MockHttpHandler`. Also create a `default.json` configuration in the `config` directory, importing the `presets/server.json` file.

Finally, in `lib` itself, create the main `main.ts` module and add `"dgt-id-proxy": "./dist/main.js"` to the `bin` object of `package.json`. Let the module create a new `ComponentsManager` with the package root as `mainModulePath`; then `register` the default config with the manager's `configRegistry`, let the manager `instantiate` the configured server from its URI, and `start` it. Also create an `index.ts`, simply re-exporting everything from the created modules. Keep this index up to date as you create new ones.

Try to build and run the package. If something is not working as expected, first look into it yourself once more, then ask your partner. If you both don't get what's wrong, ask for help.

If the basic server seems to work, write functional tests for each of the created modules, then run them to check if they indeed do what you'd expect. Also make sure that every aspect of your code is commented thoroughly, so both your partner and others can understand your code without asking you.


=== Adding routing &#10004;&#65039;

Create a `RoutedHttpRequestHandler` extending `HttpHandler` and taking a list of `HttpHandlerController` as dependency. Implement its `handle` method so that it checks the `HttpHandlerRequest` of the `HttpHandlerContext`, picks a `HttpHandlerRoute` from one of the `HttpHandlerController` (based on the path, method etc. of the request), and puts the a new `HttpHandlerContext` containing the original `HttpHandlerRequest` plus the `HttpHandlerRoute` itself through the `HttpHandler` specified in it.

Replace the `MockHttpHandler` in the configuration by a `RoutedHttpRequestHandler`, and give this router a controller with a route to the `MockHttpHandler`.


=== The null-operation: passing through &#10004;&#65039;

On a new branch, create a `PassThroughHttpRequestHandler` that takes a URL as dependency and performs the request on the URL, then parses the response and returns it.

Try if this works as intended by writing tests. Then add as many routes to the existing configuration as there are OIDC endpoints, and pass all of them through a configuration of the `PassThroughHttpRequestHandler` pointing to a (local or hosted) classic OIDC provider. Perform some OIDC requests on the proxy and check if the response is what we would expect from the proxied provider. Try the same with our Solid-compliant provider.


=== Intermezzo: returning useful errors &#10004;&#65039;

Good applications sometimes fail, but when they do they return useful errors. Since we are building a server, the best way to return errors is with correct HTTP responses. Take a look at the `util/errors` directory of the Community Solid Sever (CSS) and make sure you understand how they are used. Then implement the grunt of them in a new branch (with the exception of `SystemError` and `ErrorUtil`), add the necessary tests, and replace all current errors in our code by a more fitting one.


=== Preface: a storage solution &#10004;&#65039;

For the next steps, we will need a way to store some data that the proxied OIDC provider might not support itself. Make a new branch for this. We will follow the abstractions of the CSS, so feel free to be heavily inspired by their `KeyValueStorage` (although calling it a `~Store` might be more conventional), and it's `MemoryMap` and `JsonFile` implementations. Make sure to install all necessary dependencies, and put them in `/lib/storage`. Don't forget to write tests, equally inspired by the CSS.


=== Fixing DPoP &#10004;&#65039;

Suppose a provider has everything set for Solid-compliance except DPoP. Create a `DpopTokenRequestHandler` that takes another `HttpRequestHandler` as dependency, and watches for a `DPoP` header in the request. It rejects the request if such a header is absent. Otherwise, it performs all the necessary checks and acts accordingly (look back to your notes and the specs). If all is well, the handler creates a DPoP-less request, lets its dependency handler handle it, and then adds/changes all necessary information on the returned response, before returning a valid DPoP response itself.

Note that for some of the checks, such as checking the uniqueness of the `jti`, you will have to keep track of some data for a limited amount of time. Therefore add a `KeyValueStore` to the dependencies of the class. 

When finished, check the correct behavior of the `DpopTokenRequestHandler` by configuring it and placing it in front of an almost-Solid-OIDC-compliant provider which has no DPoP support.

For good measure, we might also create a `DpopResourceRequestHandler` implementing the second step of DPoP security: checking the DPoP-bound token and, if valid, passes the request to the dependency handler.


=== Fixing PKCE &#10004;&#65039;

In the same fashion as the `DpopRequestHandler`, create two handlers adding missing PKCE support: a `PkceAuthRequestHandler` and a `PkceTokenRequestHandler`. 

The first one watches for the `code_challenge` and `code_challenge_method` parameters. It rejects the request if one of these is absent. Otherwise, it passes a PKCE-less request through its dependency handler, stores the parameters with the authorization code of the response, and returns the response itself.

The second one watches for the `code_verifier` parameter. It rejects the request if this parameter is absent. Otherwise, it performs the check of the verifier with the stored data and, if valid, passes a PKCE-less request through its dependency handler and returns the response.


=== WebIDs on the fly &#10004;&#65039;

If an identity provider does not allow WebIDs as identities, either because of technical reasons or because of legacy identities, the proxy will have to find a way to still return a WebID to the client. Let's do this by implementing a `WebIDResponseHandler` that already takes a response as input, checks if it contains a correct `webid` claim and, if not, build one from the `sub` claim according to a WebID pattern given to the constructor. Let this pattern be similar to how the dynamic url pattern in our router works: a URL string in which the subject will be inserted instead of a tag starting with `:`. Whenever the upstream server returns a response that is not a WebID, the handler can then create on based on the subject claim and the WebID pattern. 

For now, also write a `SequenceHandler` that takes a list of handlers and passes the initial input to the first handler, takes the response thereof and passes it to the next handler, and so on until it finally returns the response of the last handler.

In the config for non-compliant providers, exchange the `PassThroughHandler` by a `SequenceHandler` with a list containing the `PassThroughHandler` as first handler and a `WebIDResponseHandler` as second.

As always: write and run test while coding, and check afterwards with a real setup.


=== Extend responses with Solid claims &#10004;&#65039;

Regardless of the correct security measures, a token is only useful if it contains the right claims. Make sure the proxied response contains these, even if the upstream server left some out. Do this by implementing a basic `SolidTokensRequestHandler` which stores the necessary information from the request in a store, passes the request to a nested handler (given as dependency in the constructor), and based on the response and the initially stored information then adds all missing claims. Use your own comparison docs to decide what can be missing, and thus what checks to do and information to add. Be especially aware of the fact that the Solid specification has prescriptions for both the Access Token _and_ the ID Token, and that the Access Token in classic OIDC can be opaque.

In the config for non-compliant providers, exchange the `PassThroughHandler` by a `SolidTokensRequestHandler` that takes the `PassThroughHandler` as nested handler.

As always: write and run test while coding, and check afterwards with a real setup.


=== Dynamic client registration

Since Solid OIDC allows clients to simply refer to their WebId for registration info, while the upstream provider might only have static clients or classic dynamic registration enabled, we should provide a handler that provides this functionality. We might want to provide two different implementations of this handler, depending on the case of the upstream server:

- One `SolidClientDynamicRegistrationHandler` that leverages the Dynamic Registration endpoint of the upstream server to check wether the client is registered (with it's up to date information from the WebID) and, if not, registers the client dynamically (or updates the clients registered information) before passing the request on through a nested handler and simply returning the response.

- One `SolidClientStaticRegistrationHandler` that takes a static client ID, a store and a nested handler as dependencies, and replaces the client's ID with its own when passing the request to the nested handler, but restores it in the response before returning it.

Beware of the fact that in either case, ephemeral Solid clients may also identify as http://www.w3.org/ns/solid/terms#PublicOidcClient, (in which case the IdP may accept any `redirect_uri`), _or_ may present an identifier that is already statically or dynamically registered.


=== Advertise Solid compliance 

Make sure the proxy advertises its Solid OIDC support in a OIDC Discovery resource.


=== Addition: launch variables

Look into the startup code of `platform-api` (link:https://github.com/digita-ai/dgt-platform/blob/develop/packages/dgt-platform-api/lib/main.ts[`lib/main.ts`], link:https://github.com/digita-ai/dgt-platform/blob/develop/packages/dgt-platform-api/bin/server.js[`bin/server.js`] and link:https://github.com/digita-ai/dgt-platform/blob/develop/packages/dgt-platform-api/config/presets/launch.json[config/presets/launch.json]) and implement a similar use of variables, at least for:

- the config path;
- the main module path;
- the host and port of the proxy;
- the host and port of the upstream server.

Since our binary file _is_ our main file, the setup will look slightly different, but not much.
