@baseUrl = http://localhost:3002

########

# @name createPod
POST {{baseUrl}}/pods HTTP/1.1
Content-Type: application/json

{
  "login": "buckylaplasse",
  "webId": "http://localhost:3002/buckylaplasse/profile/card#me",
  "name": "Bucky Laplasse",
  "email": "buckylaplasse@digita.ai"
}

########

# @name createPod
POST {{baseUrl}}/pods HTTP/1.1
Content-Type: application/json

{
  "login": "tonypaillard",
  "webId": "http://localhost:3002/tonypaillard/profile/card#me",
  "name": "Tony Paillard",
  "email": "tonypaillard@digita.ai"
}

########

# @name createPodAuth0
POST {{baseUrl}}/pods HTTP/1.1
Content-Type: application/json

{
  "login": "auth0609be5ed22684f0067d64174",
  "webId": "http://localhost:3002/auth0609be5ed22684f0067d64174/profile/card#me",
  "name": "Lea Peeters",
  "email": "auth0609be5ed22684f0067d64174@digita.ai"
}

########

# @name createPodKeycloak
POST {{baseUrl}}/pods HTTP/1.1
Content-Type: application/json

{
  "login": "944e0f16-b053-48df-b7d3-2371b680b2f3",
  "webId": "http://localhost:3002/944e0f16-b053-48df-b7d3-2371b680b2f3/profile/card#me",
  "name": "Keycloak User",
  "email": "944e0f16-b053-48df-b7d3-2371b680b2f3@digita.ai"
}

########

# @name getProfileAsTurtle
GET {{baseUrl}}/tonypaillard/profile/card HTTP/1.1
Accept: text/turtle

########

# @name createProfile
PUT {{baseUrl}}/profile/card HTTP/1.1
Content-Type: text/turtle

@prefix : <#>.
@prefix schem: <http://schema.org/>.
@prefix pro: <./>.
@prefix n0: <http://xmlns.com/foaf/0.1/>.

pro:card a n0:PersonalProfileDocument; n0:maker :me; n0:primaryTopic :me.

:me
    a schem:Person, n0:Person;
    n0:name "Tony Paillard".
    