= Keycloak

https://www.keycloak.org/[Keycloak] gives you more control than xref:auth0.adoc[Auth0], but less control than xref:oidc_provider.adoc[Node OIDC Provider].

For the proxy, Keycloak was tested using a Docker image, but there are more ways in which Keycloak can be https://www.keycloak.org/getting-started[setup].

Since you can run a Keycloak instance locally, this gives you a bit more room to configure it freely, but it's still fairly restrictive.

https://www.keycloak.org/documentation[Keycloak Documentation]

For a demo of the Keycloak provider in the root of this repository, open a terminal and execute `npm run demo:keycloak`. This will start an instance of the proxy with the correct configuration, a demo client and a demo pod server.

You can login to Keycloak using:
    * email: tonypaillard@digita.ai
    * password: Digita1234!

== Solid Compliant Features

Out of the box, PKCE is enabled. Keycloak also provides JWT access tokens by default.

== Enabling Features

You can give Keycloak a specific configuration that it should use at startup. This allows you to configure clients, realms, users, ..., almost everything that can be changed in the setup.

In terms of Solid Compliant features specifically, you have the ability to create "Protocol Mappers", which you can use to add claims to both the ID Token and the Access Token. This can be used to add the `webid` claim. However, we have not found a way of adding the string `solid` to the existing `aud` claim.

To add the `webid` claim to tokens:

. In your realm, select a client
. For that client, select the "Mappers" option, and select "Create"
. For "Mapper Type", select User Attribute.
. Set "Token Claim Name" to webid.
. Set "Add to ID token" and "Add to access token" to on.

If the claim `webid` exists on the user that is requesting a token, it will then be added to the ID Token and the Access Token.

== Features Provided by the Proxy

To make Keycloak Solid-OIDC compliant you will need to configure the following features on the proxy:

* xref:../../proxy/pages/webids_as_clientids.adoc[Using webids as client IDs]. Can be achieved with the Static Client handlers.
* xref:../../proxy/pages/dpop.adoc[Demonstrating Proof of Posession].
* xref:../../proxy/pages/claim_extension.adoc#aud[Adding `solid` to the aud claim of Access Tokens].