= Node OIDC Provider

https://github.com/panva/node-oidc-provider[Node OIDC Provider] is the most configurable of the providers. It provides you with a wide range of configuration options, and it gives you access to the specific requests and responses that are being received and sent by the Identity Provider, so you can do almost anything with it through a bit of code. It was created by https://github.com/panva[panva]

https://github.com/panva/node-oidc-provider/blob/main/docs/README.md[Node OIDC Provider Documentation]

For a demo of the Node OIDC Provider in the root of this repository, open a terminal and execute `npm run demo:panva`. This will start an instance of the proxy with the correct configuration, a demo client and a demo pod server.

You can login to Node OIDC Provider using:
    * email: tonypaillard@digita.ai
    * password: anything, as we setup the provider to accept any password.

== Solid Compliant Features

Out of the box, none are configured. You will need to configure everything yourself.

== Enabling Features

It is possible to make a completely Solid-OIDC Compliant Identity Provider using Node OIDC Provider. In fact, we have done just that. Take a look at it xref:../../../../providers/solid-compliant-oidc-provider/README.md[here].

To get started, panva has provided a https://github.com/panva/node-oidc-provider-example[step by step example] of how you can setup the provider. Note that his example will setup the provider on Heroku. You can instead take the code from that example and use it as a base for your own provider and run it locally.

To make Node OIDC Provider completely Solid-OIDC Compliant, you will have to do the following:

. Add https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#pkce[pkce] claim, and set required to a function that returns true:
+
[source, javascript]
----
pkce: {
    required: () => true
}
----
+
. Add the https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#featuresdpop[dpop] claim to the `features` claim and enable it:
+
[source, javascript]
----
features: {
    dpop:{
        enabled: true
    }
}
----
+
. Also under `features` add https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#featuresresourceindicators[resourceIndicators], enable it, and add a 'defaultResource' function, as well as a getResourceServerInfo function. This is the only way to get JWT Access Tokens in v7 of the provider:
+
[source, javascript]
----
resourceIndicators: {
    defaultResource: (ctx, client, oneOf) => {
        return 'http://example.com'
    },
    enabled: true,
    getResourceServerInfo: (ctx, resourceIndicator, client) => {
        return ({
            audience: 'solid',
            accessTokenTTL: 2 * 60 * 60, // 2 hours
            accessTokenFormat: 'jwt',
            jwt: {
                sign: { alg: 'ES256' },
            },
        });
    }
}
----
+
. Again under `features`, add https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#featuresregistration[registration] and enable it to enable Dynamic Registration:
+
[source, javascript]
----
registration: {
    enabled: true
}
----
+
. Make sure each user has a webid configured. Add https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#extratokenclaims[extraTokenClaims] function and add the `webid` claim to the Access Token:
+
[source,javascript]
----
extraTokenClaims: async function (ctx, token) {
    const account = await Account.findAccount(ctx, token.accountId)
    const claims = await account.claims()
    return ({
        'webid': claims.webid
    })

}
----
. Advertise Solid-OIDC compliance in the .well-known/openid-configuration discovery page using the https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#discovery[discovery] claim:
+
[source,javascript]
----
discovery: {
    "solid_oidc_supported": "https://solidproject.org/TR/solid-oidc"
}
----
+
. To dereference WebIDs so they can be used as ClientIDs, you will need to make use of https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#pre--and-post-middlewares[middleware] that lets you capture the request. The way we did this was by capturing the request, taking the client_id, checking that it is a valid url, and if it is, checking that it is a valid webid. Then we parse the rdf document, take the `oidcRegistration` claim and validate it. Once that is done, we leverage the Dynamic Registration endpoint on the provider to register the client, but we add an encrypted claim to the data we send to the claim so that we can verify it was sent by us. Then, we verify that claim using the registration.idFactory function.
+
This is quite a workaround, but take a look at the code of our xref:../../../../providers/solid-compliant-oidc-provider/README.md[solid-compliant-oidc-provider] if you are interested in doing the same. Otherwise, you can always skip this step and let the proxy take care of using webids as clientIDs.



== Features Provided by the Proxy

As explained, it is entirely possible to make Node OIDC Provider Solid-OIDC compliant. It might be a good idea to enable as many features as possible that are easily added through configuration such as PKCE and DPoP, and then letting the proxy handle the other things that are a lot more finnicky to implement.

Take a look at the xref:../../proxy/pages/index.adoc[list of features] that the proxy supports and see which ones you might still need to add.