#!/bin/sh
. "$(dirname $0)/_/husky.sh"

REMOTE="$1"
URL="$2"

ZERO=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid
do
    if test "$remote_oid" = "$ZERO"
    then

        # New branch
    
        BRANCH=$(git rev-parse --abbrev-ref $local_oid)
        REGEX="^(develop|master|(feat|fix|docs|chore|refactor|revert|style|perf|build|ci|test)\/[a-zA-Z0-9\-]+)$"

        if [[ ! $BRANCH =~ $REGEX ]]; then 
            echo "Please rename your branch in accordance with the following regex:" >&
            echo "$REGEX" >&
            exit 1
        fi

    fi
done

exit 0